### ISSUE TITLE
Definir entidade de objetos

### ISSUE THREAD

**Issue by sbvorpagel** [sbvorpagel/cubejs#3]
Definir a entidade de objetos. Essa entidade deve possuír uma lista de cubos e essa lista pode possír uma segunda lista de cubos (cubos agrupados).

**Comment by steuck13** [comment]
A lista de cubos não 'pode' possuir uma segunda lista de cubos, ela 'deve' possuir. Todo objeto da lista é uma lista com um OU mais objetos. Não acha melhor assim? Caso não avise que eu mudo lá.
